"""empty message

Revision ID: 24a3e1f81ca7
Revises: 7720605483e9
Create Date: 2020-01-04 19:56:34.887673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24a3e1f81ca7'
down_revision = '7720605483e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('season', sa.Integer(), nullable=False, server_default=sa.text("'12'")))
    op.add_column('orders', sa.Column('week', sa.Integer(), nullable=False, server_default=sa.text("'19'")))
    op.create_index(op.f('ix_orders_season'), 'orders', ['season'], unique=False)
    op.create_index(op.f('ix_orders_week'), 'orders', ['week'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_week'), table_name='orders')
    op.drop_index(op.f('ix_orders_season'), table_name='orders')
    op.drop_column('orders', 'week')
    op.drop_column('orders', 'season')
    # ### end Alembic commands ###
