"""empty message

Revision ID: 2629566c113c
Revises: f4529bd7d136
Create Date: 2019-08-19 11:05:51.702291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2629566c113c'
down_revision = 'f4529bd7d136'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=7), nullable=False),
    sa.Column('unit_price_change', sa.Numeric(precision=14, scale=7), nullable=False),
    sa.Column('units', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_histories')
    # ### end Alembic commands ###
