"""empty message

Revision ID: 372e1e161657
Revises: e884958e7076
Create Date: 2019-08-09 15:32:51.584244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '372e1e161657'
down_revision = 'e884958e7076'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stocks', 'unit_price',
               existing_type=sa.Numeric(14,7),
               nullable=False)
    op.alter_column('stocks', 'unit_price_change',
               existing_type=sa.Numeric(14,7),
               nullable=False)
    op.alter_column('orders', 'buy_funds',
               existing_type=sa.Numeric(14,7),
               nullable=True)
    op.alter_column('orders', 'final_price',
               existing_type=sa.Numeric(14,7),
               nullable=True)
    op.alter_column('orders', 'share_price',
               existing_type=sa.Numeric(14,7),
               nullable=True)
    op.alter_column('accounts', 'amount',
               existing_type=sa.Numeric(14,7),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stocks', 'unit_price',
               existing_type=sa.Float(),
               nullable=False)
    op.alter_column('stocks', 'unit_price_change',
               existing_type=sa.Float(),
               nullable=False)
    op.alter_column('orders', 'buy_funds',
               existing_type=sa.Float(),
               nullable=True)
    op.alter_column('orders', 'final_price',
               existing_type=sa.Float(),
               nullable=True)
    op.alter_column('orders', 'share_price',
               existing_type=sa.Float(),
               nullable=True)
    op.alter_column('accounts', 'amount',
               existing_type=sa.Float(),
               nullable=False)
    # ### end Alembic commands ###
