"""empty message

Revision ID: 4809fd1f4828
Revises: d239379c80d0
Create Date: 2020-01-03 09:10:57.781777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4809fd1f4828'
down_revision = 'd239379c80d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('ix_account_snapshots_account_id_week', 'account_snapshots', ['account_id', 'week'])
    op.create_unique_constraint('ix_accounts_user_id_season', 'accounts', ['user_id', 'season'])
    op.create_unique_constraint('ix_point_cards_user_id_season', 'point_cards', ['user_id', 'season'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ix_point_cards_user_id_season', 'point_cards', type_='unique')
    op.drop_constraint('ix_accounts_user_id_season', 'accounts', type_='unique')
    op.drop_constraint('ix_account_snapshots_account_id_week', 'account_snapshots', type_='unique')
    # ### end Alembic commands ###
