"""empty message

Revision ID: 49f6f6909594
Revises: 560079982ed7
Create Date: 2019-08-16 19:41:28.918241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49f6f6909594'
down_revision = '560079982ed7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('buy_shares', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'buy_shares')
    # ### end Alembic commands ###
