"""empty message

Revision ID: 560079982ed7
Revises: 372e1e161657
Create Date: 2019-08-12 13:38:24.946622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '560079982ed7'
down_revision = '372e1e161657'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks', sa.Column('coach', sa.String(length=30), nullable=True))
    op.add_column('stocks', sa.Column('race', sa.String(length=30), nullable=True))
    op.create_index(op.f('ix_stocks_coach'), 'stocks', ['coach'], unique=False)
    op.create_index(op.f('ix_stocks_race'), 'stocks', ['race'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stocks_race'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_coach'), table_name='stocks')
    op.drop_column('stocks', 'race')
    op.drop_column('stocks', 'coach')
    # ### end Alembic commands ###
