"""empty message

Revision ID: 7720605483e9
Revises: 4809fd1f4828
Create Date: 2020-01-04 13:08:30.555643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7720605483e9'
down_revision = '4809fd1f4828'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_position_season_weak_user', 'positions', ['user_id', 'season', 'week'], unique=True)
    op.create_index(op.f('ix_positions_season'), 'positions', ['season'], unique=False)
    op.create_index(op.f('ix_positions_week'), 'positions', ['week'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_positions_week'), table_name='positions')
    op.drop_index(op.f('ix_positions_season'), table_name='positions')
    op.drop_index('ix_position_season_weak_user', table_name='positions')
    op.drop_table('positions')
    # ### end Alembic commands ###
