"""empty message

Revision ID: 7d91770dd470
Revises: a10eeb1db030
Create Date: 2020-01-02 13:03:34.713553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d91770dd470'
down_revision = 'a10eeb1db030'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('active', sa.Boolean(), nullable=False, server_default=sa.text("'1'")))
    op.add_column('accounts', sa.Column('season', sa.Integer(), nullable=False, server_default=sa.text("'12'")))
    op.create_index(op.f('ix_accounts_season'), 'accounts', ['season'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accounts_season'), table_name='accounts')
    op.drop_column('accounts', 'season')
    op.drop_column('accounts', 'active')
    # ### end Alembic commands ###
