"""empty message

Revision ID: 80f85b57a8f4
Revises: 7d91770dd470
Create Date: 2020-01-02 13:16:16.431841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80f85b57a8f4'
down_revision = '7d91770dd470'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=7), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_snapshots_week'), 'account_snapshots', ['week'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_account_snapshots_week'), table_name='account_snapshots')
    op.drop_table('account_snapshots')
    # ### end Alembic commands ###
