"""empty message

Revision ID: a10eeb1db030
Revises: 1745ece37148
Create Date: 2019-08-23 15:41:48.823557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a10eeb1db030'
down_revision = '1745ece37148'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('division', sa.String(length=255), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('match_uuid', sa.String(length=255), nullable=True),
    sa.Column('homeCoachId', sa.Integer(), nullable=True),
    sa.Column('homeTeamId', sa.Integer(), nullable=True),
    sa.Column('homeCoachName', sa.String(length=255), nullable=True),
    sa.Column('homeTeamName', sa.String(length=255), nullable=False),
    sa.Column('homeTeamRace', sa.String(length=255), nullable=False),
    sa.Column('homeScore', sa.Integer(), nullable=True),
    sa.Column('awayCoachId', sa.Integer(), nullable=True),
    sa.Column('awayTeamId', sa.Integer(), nullable=True),
    sa.Column('awayCoachName', sa.String(length=255), nullable=True),
    sa.Column('awayTeamName', sa.String(length=255), nullable=False),
    sa.Column('awayTeamRace', sa.String(length=255), nullable=False),
    sa.Column('awayScore', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_awayCoachName'), 'matches', ['awayCoachName'], unique=False)
    op.create_index(op.f('ix_matches_awayTeamName'), 'matches', ['awayTeamName'], unique=False)
    op.create_index(op.f('ix_matches_homeCoachName'), 'matches', ['homeCoachName'], unique=False)
    op.create_index(op.f('ix_matches_homeTeamName'), 'matches', ['homeTeamName'], unique=False)
    op.create_index(op.f('ix_matches_round'), 'matches', ['round'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matches_round'), table_name='matches')
    op.drop_index(op.f('ix_matches_homeTeamName'), table_name='matches')
    op.drop_index(op.f('ix_matches_homeCoachName'), table_name='matches')
    op.drop_index(op.f('ix_matches_awayTeamName'), table_name='matches')
    op.drop_index(op.f('ix_matches_awayCoachName'), table_name='matches')
    op.drop_table('matches')
    # ### end Alembic commands ###
