"""empty message

Revision ID: a369cdaab405
Revises: 505fec4376b0
Create Date: 2019-08-07 20:54:43.413416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a369cdaab405'
down_revision = '505fec4376b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_stocks_code', table_name='stocks')
    op.create_index(op.f('ix_stocks_code'), 'stocks', ['code'], unique=True)
    op.alter_column('accounts', 'amount',
               existing_type=sa.Float(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'amount',
               existing_type=sa.Integer(),
               nullable=False)
    op.drop_index(op.f('ix_stocks_code'), table_name='stocks')
    op.create_index('ix_stocks_code', 'stocks', ['code'], unique=False)
    # ### end Alembic commands ###
