"""empty message

Revision ID: e281b65a69c1
Revises: 24a3e1f81ca7
Create Date: 2020-01-23 17:00:57.864446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e281b65a69c1'
down_revision = '24a3e1f81ca7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks', sa.Column('deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stocks', 'deleted')
    # ### end Alembic commands ###
