"""empty message

Revision ID: e884958e7076
Revises: a369cdaab405
Create Date: 2019-08-09 14:57:05.044063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e884958e7076'
down_revision = 'a369cdaab405'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks', sa.Column('unit_price_change', sa.Float(), nullable=False, server_default=sa.text("'0.0'")))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stocks', 'unit_price_change')
    # ### end Alembic commands ###
