"""empty message

Revision ID: f4529bd7d136
Revises: 49f6f6909594
Create Date: 2019-08-18 20:13:38.171100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4529bd7d136'
down_revision = '49f6f6909594'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks', sa.Column('division', sa.String(length=30), nullable=True))
    op.create_index(op.f('ix_stocks_division'), 'stocks', ['division'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stocks_division'), table_name='stocks')
    op.drop_column('stocks', 'division')
    # ### end Alembic commands ###
